<?php

require_once __DIR__ . '/../validation.php';
ensureSessionStarted();

// Protect Instructor Portal
if (!isset($_SESSION['user_id']) || ($_SESSION['role_name'] ?? '') !== 'instructor') {
    header('Location: ../login.php?status=error&message=' . urlencode('Please log in with an instructor account.'));
    exit;
}

require_once __DIR__ . '/../database/config.php';

$instructorId = (int)$_SESSION['user_id'];
$courseId     = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if ($courseId <= 0) {
    header('Location: dashboard.php?status=error&message=' . urlencode('Invalid course ID provided.'));
    exit;
}

try {
    $pdo = getConnection();

    // 1. Fetch Instructor Details
    $stmtUser = $pdo->prepare("SELECT id, full_name, email FROM users WHERE id = :id AND role_id = 2 LIMIT 1");
    $stmtUser->execute([':id' => $instructorId]);
    $instructor = $stmtUser->fetch();

    if (!$instructor) {
        header('Location: ../login.php?status=error&message=' . urlencode('Instructor account not found.'));
        exit;
    }

    // 2. Fetch Course Details (Must belong to this instructor)
    $stmtCourse = $pdo->prepare("SELECT * FROM courses WHERE id = :cid AND instructor_id = :iid LIMIT 1");
    $stmtCourse->execute([':cid' => $courseId, ':iid' => $instructorId]);
    $course = $stmtCourse->fetch();

    if (!$course) {
        header('Location: dashboard.php?status=error&message=' . urlencode('Course not found or you do not have permission to view it.'));
        exit;
    }

    // 3. Fetch Lessons for this Course
    $stmtLessons = $pdo->prepare("SELECT * FROM lessons WHERE course_id = :cid ORDER BY lesson_number ASC");
    $stmtLessons->execute([':cid' => $courseId]);
    $lessons = $stmtLessons->fetchAll();
    $totalLessonsCount = count($lessons) > 0 ? count($lessons) : (int)($course['total_lessons'] ?? 1);

    // 4. Fetch Course Performance Metrics (No average progress per instructor preference)
    // Enrolled students count
    $stmtEnrolled = $pdo->prepare("SELECT COUNT(DISTINCT user_id) FROM enrollments WHERE course_id = :cid");
    $stmtEnrolled->execute([':cid' => $courseId]);
    $totalEnrolled = (int)$stmtEnrolled->fetchColumn();

    // Certificates awarded count
    $stmtCerts = $pdo->prepare("SELECT COUNT(DISTINCT id) FROM certificates WHERE course_id = :cid");
    $stmtCerts->execute([':cid' => $courseId]);
    $totalCertificates = (int)$stmtCerts->fetchColumn();

    // Ad revenue generated by this course
    $stmtAdRev = $pdo->prepare("SELECT COALESCE(SUM(amount_earned), 0) AS total_revenue, COUNT(id) AS total_views 
                                FROM ad_activity_logs 
                                WHERE course_id = :cid AND instructor_id = :iid");
    $stmtAdRev->execute([':cid' => $courseId, ':iid' => $instructorId]);
    $adData = $stmtAdRev->fetch();
    $totalAdRevenue = (float)($adData['total_revenue'] ?? 0);
    $totalAdViews   = (int)($adData['total_views'] ?? 0);

    // 5. Fetch Enrolled Students & Their Progress Roster
    $sqlStudents = "SELECT 
                        u.id AS student_id,
                        u.full_name AS student_name,
                        u.email AS student_email,
                        e.progress_percent,
                        e.status AS enrollment_status,
                        e.enrolled_at,
                        e.completed_at,
                        COUNT(DISTINCT lc.lesson_id) AS completed_lessons_count,
                        cert.certificate_code,
                        cert.issued_at AS cert_issued_at,
                        sub.id AS submission_id,
                        sub.submission_type,
                        sub.submission_value,
                        sub.notes AS submission_notes,
                        sub.instructor_feedback,
                        sub.status AS submission_status,
                        sub.submitted_at
                    FROM enrollments e
                    JOIN users u ON e.user_id = u.id
                    LEFT JOIN lesson_completions lc ON lc.user_id = u.id AND lc.course_id = e.course_id
                    LEFT JOIN certificates cert ON cert.user_id = u.id AND cert.course_id = e.course_id
                    LEFT JOIN (
                        SELECT cs1.*
                        FROM course_submissions cs1
                        INNER JOIN (
                            SELECT MAX(id) AS max_id
                            FROM course_submissions
                            GROUP BY user_id, course_id
                        ) cs2 ON cs1.id = cs2.max_id
                    ) sub ON sub.user_id = u.id AND sub.course_id = e.course_id
                    WHERE e.course_id = :cid
                    GROUP BY u.id, e.id
                    ORDER BY e.enrolled_at DESC";
    $stmtStudents = $pdo->prepare($sqlStudents);
    $stmtStudents->execute([':cid' => $courseId]);
    $students = $stmtStudents->fetchAll();

    // 6. Lesson completion stats (how many students finished each lesson)
    $lessonCompletionStats = [];
    if (!empty($lessons)) {
        $stmtLessonStats = $pdo->prepare("SELECT lesson_id, COUNT(DISTINCT user_id) AS completions_count 
                                          FROM lesson_completions 
                                          WHERE course_id = :cid 
                                          GROUP BY lesson_id");
        $stmtLessonStats->execute([':cid' => $courseId]);
        while ($row = $stmtLessonStats->fetch()) {
            $lessonCompletionStats[(int)$row['lesson_id']] = (int)$row['completions_count'];
        }
    }

    // 7. Total Courses count (for sidebar badge)
    $stmtCountCourses = $pdo->prepare("SELECT COUNT(*) FROM courses WHERE instructor_id = :iid");
    $stmtCountCourses->execute([':iid' => $instructorId]);
    $totalCoursesCount = (int)$stmtCountCourses->fetchColumn();

    // 8. Total Submissions count (for sidebar badge)
    $stmtCountSubs = $pdo->prepare("SELECT COUNT(sub.id) FROM course_submissions sub JOIN courses c ON sub.course_id = c.id WHERE c.instructor_id = :iid");
    $stmtCountSubs->execute([':iid' => $instructorId]);
    $totalSubmissionsCount = (int)$stmtCountSubs->fetchColumn();

    // 9. Wallet total earned (for sidebar badge)
    $stmtWallet = $pdo->prepare("SELECT total_earned FROM instructor_wallets WHERE instructor_id = :iid LIMIT 1");
    $stmtWallet->execute([':iid' => $instructorId]);
    $totalEarnedWallet = (float)($stmtWallet->fetchColumn() ?: 0);

} catch (PDOException $e) {
    error_log('Instructor course overview error: ' . $e->getMessage());
    header('Location: dashboard.php?status=error&message=' . urlencode('An error occurred while loading the course overview.'));
    exit;
}

$initials = strtoupper(substr($instructor['full_name'] ?? 'I', 0, 1));
$thumbSrc = !empty($course['thumbnail']) && str_starts_with($course['thumbnail'], 'uploads/')
    ? '../' . $course['thumbnail']
    : '../assets/adsity_assets/' . ($course['thumbnail'] ?: 'Web_Development_Basics.png');

$assessmentTypeNames = [
    'github_repo' => 'GitHub Repository Submission',
    'file_upload' => 'Project Archive / File Upload',
    'live_url'    => 'Live Hosted Application URL',
];
$assessmentName = $assessmentTypeNames[$course['assessment_type']] ?? 'Project Deliverable';
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?= htmlspecialchars($course['title']) ?> - Course Overview | Adsity Instructor Studio</title>
	<link rel="stylesheet" href="../style.css">
	<link rel="stylesheet" href="instructordashboard.css">
	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>

<body class="instructor-dashboard-body">

	<!-- Top Navigation Header -->
	<header class="instructor-navbar">
		<div class="instructor-nav-left">
			<button type="button" class="sidebar-toggle-btn" id="sidebarToggle" aria-label="Toggle Navigation Menu">
				<span class="hamburger-line"></span>
				<span class="hamburger-line"></span>
				<span class="hamburger-line"></span>
			</button>

			<a href="dashboard.php" class="instructor-nav-logo" title="Adsity Home">
				<img src="../assets/adsity_assets/Adsity_Logo.png" alt="Adsity Logo">
			</a>
			<span class="studio-badge-title">Instructor Studio</span>
		</div>

		<div class="instructor-nav-right">
			<a href="dashboard.php" class="instructor-nav-link" style="display: inline-flex; align-items: center; gap: 6px;">
				<img src="../assets/icons/arrow-left.svg" width="14" height="14" alt="Back">
				<span>Back to Dashboard</span>
			</a>
			<a href="create_course.php" class="nav-btn-create">
				<img src="../assets/icons/plus.svg" width="15" height="15" alt="Create" style="filter: brightness(0) invert(1);">
				<span>Create Course</span>
			</a>
			<a href="../courses.php" class="instructor-nav-link">Explore Catalog</a>
			<div class="instructor-user-pill">
				<div class="instructor-user-avatar"><?= $initials ?></div>
				<span class="instructor-user-name" title="<?= htmlspecialchars($instructor['full_name'] ?? 'Instructor') ?>">
					<?= htmlspecialchars($instructor['full_name'] ?? 'Instructor') ?>
				</span>
			</div>
			<a href="../logout.php" class="instructor-btn-logout">
				<img src="../assets/icons/arrow-left.svg" width="14" height="14" alt="Logout">
				<span>Log Out</span>
			</a>
		</div>
	</header>

	<!-- App Layout: Left Sidebar Navbar + Main Content Area -->
	<div class="instructor-dashboard-layout">

		<!-- ==========================================
		     LEFT SIDEBAR NAVBAR (ALL INSTRUCTOR ACTIONS)
		     ========================================== -->
		<aside class="instructor-sidebar" id="instructorSidebar">
			<div class="sidebar-top-section">

				<!-- Instructor Profile Summary Card -->
				<div class="instructor-profile-card">
					<div class="instructor-profile-avatar"><?= $initials ?></div>
					<div class="instructor-profile-info">
						<div class="instructor-profile-name" title="<?= htmlspecialchars($instructor['full_name'] ?? 'Instructor') ?>">
							<?= htmlspecialchars($instructor['full_name'] ?? 'Instructor') ?>
						</div>
						<div class="instructor-profile-status">
							<span class="status-indicator-dot"></span>
							Ad Revenue Partner
						</div>
					</div>
				</div>

				<!-- Prominent Primary Action Button -->
				<div class="sidebar-cta-wrapper">
					<a href="create_course.php" class="btn-sidebar-create">
						<img src="../assets/icons/plus.svg" width="16" height="16" alt="Add" style="filter: brightness(0) invert(1);">
						<span>Publish New Course</span>
					</a>
				</div>

				<!-- Navigation Actions & Tabs -->
				<nav class="sidebar-nav-group">
					<div class="sidebar-group-label">Studio Actions</div>

					<a href="dashboard.php#overview" class="sidebar-nav-item">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/layout.svg" class="sidebar-nav-icon" alt="Overview">
							<span>Dashboard Overview</span>
						</div>
					</a>

					<a href="dashboard.php#courses" class="sidebar-nav-item active">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/book-open.svg" class="sidebar-nav-icon" alt="Courses">
							<span>My Courses</span>
						</div>
						<span class="sidebar-badge-count"><?= $totalCoursesCount ?></span>
					</a>

					<a href="dashboard.php#submissions" class="sidebar-nav-item">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/award.svg" class="sidebar-nav-icon" alt="Submissions">
							<span>Student Submissions</span>
						</div>
						<span class="sidebar-badge-count"><?= $totalSubmissionsCount ?></span>
					</a>

					<a href="dashboard.php#revenue" class="sidebar-nav-item">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/dollar-sign.svg" class="sidebar-nav-icon" alt="Revenue">
							<span>Ad Revenue &amp; Logs</span>
						</div>
						<span class="sidebar-badge-share">$<?= number_format($totalEarnedWallet, 2) ?></span>
					</a>

					<div class="sidebar-group-label" style="margin-top: 22px;">Explore Platform</div>

					<a href="../courses.php" class="sidebar-nav-item">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/globe.svg" class="sidebar-nav-icon" alt="Courses">
							<span>Course Catalog</span>
						</div>
					</a>

					<a href="../index.php" class="sidebar-nav-item">
						<div class="sidebar-nav-item-left">
							<img src="../assets/icons/external-link.svg" class="sidebar-nav-icon" alt="Home">
							<span>Platform Homepage</span>
						</div>
					</a>
				</nav>
			</div>

			<!-- Sidebar Footer -->
			<div class="sidebar-bottom-section">
				<div class="partner-perk-box">
					<div class="perk-title">
						<img src="../assets/icons/shield-check.svg" width="16" height="16" alt="Partner">
						<span>Partner Status</span>
					</div>
					<p class="perk-desc">Enjoying 70% ad revenue split for all published video lessons.</p>
				</div>

				<a href="../logout.php" class="btn-sidebar-logout">
					<img src="../assets/icons/arrow-left.svg" width="15" height="15" alt="Logout">
					<span>Log Out</span>
				</a>
			</div>
		</aside>

		<!-- Backdrop for mobile sidebar drawer -->
		<div class="sidebar-backdrop" id="sidebarBackdrop" onclick="toggleSidebar()"></div>

		<!-- ==========================================
		     RIGHT MAIN FLUID CONTENT
		     ========================================== -->
		<main class="instructor-main-content">

			<!-- Breadcrumbs & Navigation -->
			<div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px; flex-wrap: wrap; gap: 12px;">
				<a href="dashboard.php#courses" style="display: inline-flex; align-items: center; gap: 8px; text-decoration: none; color: var(--primary-blue); font-weight: 800; font-size: 0.95rem;">
					<img src="../assets/icons/arrow-left.svg" width="16" height="16" alt="Back" style="filter: invert(47%) sepia(85%) saturate(1412%) hue-rotate(174deg) brightness(93%) contrast(92%);">
					<span>&larr; Return to My Courses</span>
				</a>

				<div style="display: flex; gap: 10px; flex-wrap: wrap;">
					<a href="../course_details.php?id=<?= $course['id'] ?>" target="_blank" class="btn-view-course" style="background-color: #ffffff; padding: 8px 16px; font-size: 0.85rem;">
						<img src="../assets/icons/external-link.svg" width="14" height="14" alt="Preview">
						<span>View Public Course Page ↗</span>
					</a>
					<a href="../student/learn.php?course_id=<?= $course['id'] ?>" target="_blank" class="btn-view-course" style="background-color: #0284c7; color: #ffffff; padding: 8px 16px; font-size: 0.85rem; border: none;">
						<img src="../assets/icons/play.svg" width="14" height="14" alt="Player" style="filter: brightness(0) invert(1);">
						<span>Classroom Video Player ↗</span>
					</a>
				</div>
			</div>

		<!-- Course Hero Overview Card -->
		<div class="course-hero-overview-card" style="background: #ffffff; border: 1px solid var(--border-light); border-radius: 14px; padding: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); display: flex; gap: 24px; align-items: flex-start; margin-bottom: 24px;">
			<img 
				src="<?= htmlspecialchars($thumbSrc) ?>" 
				alt="<?= htmlspecialchars($course['title']) ?>" 
				style="width: 200px; height: 125px; object-fit: cover; border-radius: 10px; border: 1px solid var(--border-light); flex-shrink: 0;"
				onerror="this.src='../assets/adsity_assets/Web_Development_Basics.png'"
			>

			<div style="flex: 1; min-width: 0;">
				<div style="display: flex; align-items: center; gap: 10px; margin-bottom: 8px;">
					<span class="category-pill"><?= htmlspecialchars($course['category'] ?? 'Course') ?></span>
					<span style="font-size: 0.8rem; color: #64748b;">Published on <?= date('M d, Y', strtotime($course['created_at'])) ?></span>
				</div>

				<h1 style="font-size: 1.5rem; font-weight: 800; color: #0f172a; margin: 0 0 8px 0; line-height: 1.25;">
					<?= htmlspecialchars($course['title']) ?>
				</h1>

				<p style="color: #475569; font-size: 0.9rem; line-height: 1.5; margin: 0 0 12px 0; max-width: 820px;">
					<?= htmlspecialchars($course['description'] ?? 'No description provided.') ?>
				</p>

				<div style="display: flex; align-items: center; gap: 18px; font-size: 0.85rem; color: #64748b;">
					<div style="display: flex; align-items: center; gap: 6px;">
						<img src="../assets/icons/video.svg" width="15" height="15" alt="Lessons">
						<span><strong><?= $totalLessonsCount ?></strong> Video Modules</span>
					</div>
					<div style="display: flex; align-items: center; gap: 6px;">
						<img src="../assets/icons/award.svg" width="15" height="15" alt="Deliverable">
						<span><strong><?= htmlspecialchars($assessmentName) ?></strong></span>
					</div>
				</div>
			</div>
		</div>

		<!-- Course Performance Metrics (3 Clean Stat Cards) -->
		<div class="stats-grid" style="margin-bottom: 28px;">
			<!-- Enrolled Learners -->
			<div class="stat-card">
				<div class="stat-icon-box stat-icon-box--blue">
					<img src="../assets/icons/users.svg" width="24" height="24" alt="Students">
				</div>
				<div>
					<div class="stat-number"><?= number_format($totalEnrolled) ?></div>
					<div class="stat-label">Enrolled Learners</div>
				</div>
			</div>

			<!-- Certificates Issued -->
			<div class="stat-card">
				<div class="stat-icon-box stat-icon-box--green">
					<img src="../assets/icons/award.svg" width="24" height="24" alt="Certificates">
				</div>
				<div>
					<div class="stat-number"><?= number_format($totalCertificates) ?></div>
					<div class="stat-label">Certificates Awarded</div>
				</div>
			</div>

			<!-- Ad Revenue Earned -->
			<div class="stat-card">
				<div class="stat-icon-box stat-icon-box--purple">
					<img src="../assets/icons/dollar-sign.svg" width="24" height="24" alt="Revenue">
				</div>
				<div>
					<div class="stat-number">$<?= number_format($totalAdRevenue, 2) ?></div>
					<div class="stat-label">Ad Revenue Earned (<?= number_format($totalAdViews) ?> Views)</div>
				</div>
			</div>
		</div>

		<!-- ============================================================
		     MAIN SECTION: ENROLLED STUDENTS & INDIVIDUAL PROGRESS ROSTER
		     ============================================================ -->
		<section class="dashboard-section" style="margin-bottom: 32px;">
			<div class="section-header">
				<div>
					<h2 class="section-title">
						<img src="../assets/icons/users.svg" width="22" height="22" alt="Learners">
						Enrolled Students &amp; Progress Roster
					</h2>
					<p class="section-subtitle">Real-time breakdown of learners actively taking your course and their current milestone completion.</p>
				</div>
				<span class="section-badge-count"><?= count($students) ?> Students</span>
			</div>

			<div class="table-responsive">
				<?php if (!empty($students)): ?>
					<table class="data-table">
						<thead>
							<tr>
								<th>Student</th>
								<th>Enrolled Date</th>
								<th>Lessons Completed</th>
								<th style="min-width: 180px;">Progress</th>
								<th>Status</th>
								<th>Deliverable / Exam</th>
								<th>Certificate</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($students as $s): ?>
								<?php
								$pct = (int)($s['progress_percent'] ?? 0);
								$completedCount = (int)($s['completed_lessons_count'] ?? 0);
								$studentInitials = strtoupper(substr($s['student_name'] ?? 'S', 0, 1));
								?>
								<tr>
									<!-- Student Identity -->
									<td>
										<div style="display: flex; align-items: center; gap: 12px;">
											<div style="width: 34px; height: 34px; border-radius: 50%; background: linear-gradient(135deg, #0284c7 0%, #0369a1 100%); color: #ffffff; font-weight: 800; font-size: 0.85rem; display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
												<?= $studentInitials ?>
											</div>
											<div>
												<strong style="color: #0f172a; font-size: 0.95rem; display: block;">
													<?= htmlspecialchars($s['student_name']) ?>
												</strong>
												<span style="font-size: 0.8rem; color: #64748b;">
													<?= htmlspecialchars($s['student_email']) ?>
												</span>
											</div>
										</div>
									</td>

									<!-- Enrollment Date -->
									<td>
										<?= date('M d, Y', strtotime($s['enrolled_at'])) ?>
									</td>

									<!-- Completed Lessons Count -->
									<td>
										<strong><?= $completedCount ?></strong> of <?= $totalLessonsCount ?> Lessons
									</td>

									<!-- Progress Bar -->
									<td>
										<div style="display: flex; align-items: center; gap: 10px;">
											<div style="flex: 1; height: 7px; background-color: #e2e8f0; border-radius: 9999px; overflow: hidden;">
												<div style="height: 100%; width: <?= $pct ?>%; background: <?= $pct >= 100 ? '#16a34a' : 'linear-gradient(90deg, #0284c7 0%, #16a34a 100%)' ?>; border-radius: 9999px; transition: width 0.3s ease;"></div>
											</div>
											<span style="font-size: 0.82rem; font-weight: 800; color: <?= $pct >= 100 ? '#16a34a' : '#0f172a' ?>; min-width: 36px; text-align: right;">
												<?= $pct ?>%
											</span>
										</div>
									</td>

									<!-- Status Badge -->
									<td>
										<?php if ($pct >= 100): ?>
											<span style="background-color: #dcfce7; color: #15803d; padding: 4px 10px; border-radius: 9999px; font-size: 0.76rem; font-weight: 800; display: inline-flex; align-items: center; gap: 4px;">
												✓ Completed
											</span>
										<?php elseif ($pct > 0): ?>
											<span style="background-color: #e0f2fe; color: #0369a1; padding: 4px 10px; border-radius: 9999px; font-size: 0.76rem; font-weight: 800; display: inline-flex; align-items: center; gap: 4px;">
												▶ In Progress
											</span>
										<?php else: ?>
											<span style="background-color: #f1f5f9; color: #64748b; padding: 4px 10px; border-radius: 9999px; font-size: 0.76rem; font-weight: 700;">
												Not Started
											</span>
										<?php endif; ?>
									</td>

									<!-- Project Deliverable Submission -->
									<td>
										<?php if (!empty($s['submission_value'])): ?>
											<div style="display: flex; flex-direction: column; gap: 4px; align-items: flex-start;">
												<?php if (($s['submission_status'] ?? '') === 'approved'): ?>
													<span style="background-color: #dcfce7; color: #15803d; padding: 2px 8px; border-radius: 9999px; font-size: 0.72rem; font-weight: 800;">✓ Approved</span>
												<?php elseif (($s['submission_status'] ?? '') === 'revision_needed'): ?>
													<span style="background-color: #ffedd5; color: #c2410c; padding: 2px 8px; border-radius: 9999px; font-size: 0.72rem; font-weight: 800;">↺ Revision Needed</span>
												<?php else: ?>
													<span style="background-color: #fef3c7; color: #b45309; padding: 2px 8px; border-radius: 9999px; font-size: 0.72rem; font-weight: 800;">Pending Review</span>
												<?php endif; ?>

												<?php if ($s['submission_type'] === 'file_upload'): ?>
													<a href="../assets/submissions/<?= htmlspecialchars($s['submission_value']) ?>" download style="color: var(--primary-blue); font-weight: 700; font-size: 0.82rem; text-decoration: none; display: inline-flex; align-items: center; gap: 4px;">
														<img src="../assets/icons/download.svg" width="12" height="12" alt="File">
														<span>Download File</span>
													</a>
												<?php else: ?>
													<a href="<?= htmlspecialchars($s['submission_value']) ?>" target="_blank" rel="noopener noreferrer" style="color: var(--primary-blue); font-weight: 700; font-size: 0.82rem; text-decoration: none; display: inline-flex; align-items: center; gap: 4px;">
														<img src="../assets/icons/external-link.svg" width="12" height="12" alt="Link">
														<span>View Deliverable ↗</span>
													</a>
												<?php endif; ?>
											</div>
										<?php else: ?>
											<span style="color: #94a3b8; font-size: 0.82rem; font-style: italic;">
												<?= $pct >= 100 ? 'Pending Submission' : 'Locked' ?>
											</span>
										<?php endif; ?>
									</td>

									<!-- Certificate -->
									<td>
										<?php if (!empty($s['certificate_code'])): ?>
											<a href="../student/certificate.php?code=<?= urlencode($s['certificate_code']) ?>" target="_blank" style="background-color: #f0fdf4; border: 1px solid #bbf7d0; color: #166534; padding: 4px 10px; border-radius: 6px; font-size: 0.78rem; font-weight: 800; text-decoration: none; display: inline-flex; align-items: center; gap: 4px;">
												<img src="../assets/icons/award.svg" width="13" height="13" alt="Award">
												<span><?= htmlspecialchars($s['certificate_code']) ?> ↗</span>
											</a>
										<?php else: ?>
											<span style="color: #94a3b8; font-size: 0.82rem;">—</span>
										<?php endif; ?>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				<?php else: ?>
					<div class="empty-state" style="padding: 48px 20px; text-align: center; background: #ffffff; border-radius: 12px; border: 1px dashed #cbd5e1;">
						<img src="../assets/icons/users.svg" width="48" height="48" alt="No students" style="opacity: 0.35; margin-bottom: 12px;">
						<h3 style="font-size: 1.15rem; font-weight: 800; color: #0f172a; margin: 0 0 6px 0;">No Students Enrolled Yet</h3>
						<p style="color: #64748b; font-size: 0.88rem; margin: 0 0 16px 0;">When learners enroll in this course, their profiles and real-time lesson progress will populate here.</p>
						<a href="../course_details.php?id=<?= $course['id'] ?>" target="_blank" class="btn-create-course-hero" style="display: inline-flex; font-size: 0.85rem; padding: 8px 16px;">
							<span>View Public Course Page</span>
						</a>
					</div>
				<?php endif; ?>
			</div>
		</section>

		<!-- ============================================================
		     SECONDARY SECTION: CURRICULUM SYLLABUS BREAKDOWN
		     ============================================================ -->
		<section class="dashboard-section">
			<div class="section-header">
				<div>
					<h2 class="section-title">
						<img src="../assets/icons/book-open.svg" width="22" height="22" alt="Curriculum">
						Course Modules &amp; Video Lessons
					</h2>
					<p class="section-subtitle">Sequential curriculum modules with duration and learner completion counts.</p>
				</div>
				<span class="section-badge-count"><?= count($lessons) ?> Modules</span>
			</div>

			<div class="table-responsive">
				<?php if (!empty($lessons)): ?>
					<table class="data-table">
						<thead>
							<tr>
								<th>#</th>
								<th>Module / Lesson Title</th>
								<th>Duration</th>
								<th>Sponsor Break</th>
								<th>Learner Completions</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($lessons as $l): ?>
								<?php $comp = $lessonCompletionStats[(int)$l['id']] ?? 0; ?>
								<tr>
									<td>
										<strong style="color: #0284c7;">
											Lesson <?= str_pad($l['lesson_number'], 2, '0', STR_PAD_LEFT) ?>
										</strong>
									</td>
									<td>
										<strong style="color: #0f172a; font-size: 0.95rem;">
											<?= htmlspecialchars($l['title']) ?>
										</strong>
									</td>
									<td>
										<div style="display: flex; align-items: center; gap: 6px; color: #64748b; font-size: 0.85rem;">
											<img src="../assets/icons/clock.svg" width="14" height="14" alt="Duration">
											<span><?= htmlspecialchars($l['duration'] ?: '10:00') ?></span>
										</div>
									</td>
									<td>
										<span style="background-color: #fef3c7; color: #b45309; padding: 3px 8px; border-radius: 9999px; font-size: 0.74rem; font-weight: 800;">
											15s Ad Session
										</span>
									</td>
									<td>
										<strong><?= number_format($comp) ?></strong> completed
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				<?php else: ?>
					<div class="empty-state" style="padding: 30px; text-align: center; background: #ffffff; border-radius: 10px;">
						<p style="color: #64748b; margin: 0;">No individual lessons mapped to this course.</p>
					</div>
				<?php endif; ?>
			</div>
		</section>

		</main>
	</div>

	<!-- Bottom Footer -->
	<footer class="footer">
		<div class="footer-bottom">
			<div class="footer-bottom-inner" style="max-width: 1240px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 16px;">
				<div style="display: flex; align-items: center; gap: 12px;">
					<img src="../assets/adsity_assets/Adsity_Logo.png" alt="Adsity Logo" class="footer-bottom-logo-img">
					<p class="footer-copyright">&copy; 2026 Adsity Instructor Studio. All rights reserved.</p>
				</div>
				<div style="display: flex; align-items: center; gap: 18px; font-size: 0.85rem;">
					<a href="dashboard.php" style="color: var(--text-muted); text-decoration: none; font-weight: 600;">Studio Dashboard</a>
					<a href="../courses.php" style="color: var(--text-muted); text-decoration: none; font-weight: 600;">Explore Catalog</a>
					<a href="../course_details.php?id=<?= $course['id'] ?>" target="_blank" style="color: var(--primary-blue); text-decoration: none; font-weight: 700;">Public Course Page ↗</a>
				</div>
			</div>
		</div>
	</footer>

	<!-- Reusable UI & Client-side Helpers -->
	<script src="../assets/js/adsity-ui.js"></script>
	<script>
		function toggleSidebar() {
			AdsityUI.toggleSidebar('instructorSidebar', 'sidebarBackdrop');
		}

		function closeSidebar() {
			AdsityUI.closeSidebar('instructorSidebar', 'sidebarBackdrop');
		}

		document.addEventListener('DOMContentLoaded', function() {
			var toggleBtn = document.getElementById('sidebarToggle');
			if (toggleBtn) {
				toggleBtn.addEventListener('click', toggleSidebar);
			}
		});
	</script>
	<script src="../assets/js/logout_modal.js"></script>
</body>
</html>
